#packages#####
suppressWarnings(suppressMessages(library(ggplot2)))
suppressWarnings(suppressMessages(library(reshape2)))
suppressWarnings(suppressMessages(library(tidyverse)))
suppressWarnings(suppressMessages(library(ggpubr)))
suppressWarnings(suppressMessages(library(ggtext)))
suppressWarnings(suppressMessages(library(grid)))
suppressWarnings(suppressMessages(library(patchwork)))
suppressWarnings(suppressMessages(library(ggnewscale)))
suppressWarnings(suppressMessages(library(ggrepel)))
#paths#####
go_ps_ctrl <- read.csv("./PBMCSLEctrl-ps_cluster_top_gene100_GO_ctrl_summary[2000max].csv")
go_ps_exper <- read.csv("./PBMCSLEctrl-ps_cluster_top_gene100_GO_exper_summary[2000max].csv")
go_fast_ctrl <- read.csv("./PBMCSLEctrl_cluster_top_gene100_GO_ctrl_summary.csv")
go_fast_exper <- read.csv("./PBMCSLEctrl_cluster_top_gene100_GO_exper_summary.csv")

#function####
#' Extracting the legend of a ggplot object.
#'
#' param a.gplot: a ggplot object.
#' return the legend of the ggplot object, a gtable object.
g_legend<-function(a.gplot){
  ## extract legend 
  tmp <- ggplot_gtable(ggplot_build(a.gplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)
  }

#' Performing GO enrichment of top relevant genes clusters of PBMC-ctrl dataset 
#' generated by GeneClust-ps and GeneClust-fast.
#' 
#' param method: a character of the method to generate GOBPs enrichment.
#' param pwnum: the number of top significant GOBPs in experimental group and 
#'              control group.
#' return gtable object.
GO_point_plot <- function(method,pwnum){
  ## choose data sheet 
  if(method =="GO-ps"){
    random <- go_ps_ctrl
    ps <- go_ps_exper
  }
  if(method =="GO-fast"){
    random <- go_fast_ctrl
    ps <- go_fast_exper
  }
  ## extract needed rows and columns
  random <- random[1:pwnum,c("ID","p.adjust","Count","auc","is_immune")]
  ps <- ps[1:pwnum,c("ID","p.adjust","Count","auc","is_immune")]
  
  random[,'method'] <- "random"
  ps[,'method'] <- "ps"
  
  random$count1 <- NA
  ps$count1 <- ps$Count
  random$count2 <- random$Count
  ps$count2 <- NA
  
  combine <- rbind(random,ps)
  combine$recode <- ifelse(combine$is_immune=="1",9,99)
  
  ## plots adjustment
  if(method == "GO-ps"){
    xl <-c(0.6,7)
    size_lim <- c(0,10)
    size_br <- c(3,6,9)
    plot_mar <- unit(c(0.5,1.5,0.5,0.5),'cm')
  }
  if(method=="GO-fast"){
    xl <-c(0.5,8)
    size_lim <- c(0,18)
    size_br <- c(5,10,15)
    plot_mar <- unit(c(0.5,1.6,0.5,0.5),'cm')
  }
  ## generate plot
    p00 <- ggplot(combine,aes(x = -log10(p.adjust), y = auc))+
           geom_point(aes(size = count1),color = "transparent",shape = 19)+
           scale_size_continuous(limits = size_lim,breaks = size_br,labels = c("","",""),
                            range = c(-1.5,6),guide = guide_legend(order = 3,
                                                                   override.aes = list(color = "black"),
                                                                   title = "Count"))+
           new_scale("size")+
           geom_point(aes(size = count2),color = "transparent",shape = 17)+
           scale_size_continuous(limits = size_lim,breaks = size_br,
                            range = c(-1.5,6),guide = guide_legend(order = 4,
                                                                   override.aes = list(color = "black"),
                                                                   title = " "))+
           new_scale("size")+
           geom_point(aes(size = Count,color = recode,shape = method))+
           geom_text_repel(aes(label = ID),color = "black",size = 2.5,max.overlaps = 30,
                      segment.size = 0.3,force = 5,segment.color = "grey40")+
           scale_size_continuous(limits = size_lim,breaks = size_br,
                            range = c(-1.5,6),guide = "none")+
           scale_shape_manual(values = c("ps" = 19,"random"=17),
                         labels = c("Experiment","Control"))+
           labs(shape = "Method")+
           theme_classic()+ labs( x = "-log p.adjust", y = "AUC")+
           coord_cartesian(ylim = c(0,1),xlim = xl,clip = "off")+
           scale_color_steps(breaks = c(10),limits = c(0,100),
                        labels = c(" "),high = "#f20c00" ,low = "#44cef6",
                        name = "",na.value = "transparent")+
           theme(axis.title = element_text(size = 12),
                 axis.text = element_text(size = 10,color = "black"),
                 legend.title = element_text(size = 12),
                 legend.background = element_rect(color= "transparent",fill = "transparent"),
                 legend.key= element_rect(color = "transparent", 
                                     fill = "transparent"),
                 legend.text = element_text(size = 10),
                 legend.position = "right",
                 plot.margin = plot_mar)+
            guides(shape = guide_legend(order = 1,override.aes = list(size = 2.5)),
                 color = guide_colorsteps(order = 2,reverse = T,barwidth = 1, barheight = 3),
                 fill = "none")
    if(method == "GO-ps"){
      p0 <- p00 + annotate("text",label = "immune-related",x = 8.62,y = 0.56)+
        annotate("text",label = "immune-unrelated",x = 8.72,y = 0.487)
    }
    if(method=="GO-fast"){
      p0 <- p00 + annotate("text",label = "immune-related",x = 9.92,y = 0.56)+
        annotate("text",label = "immune-unrelated",x = 10.04,y = 0.487)
    }
  
  ## legend adjustment
  legend <- g_legend(p0)
  legend$grobs[[1]]$heights[1] <- unit(3, "cm")
  legend$grobs[[2]]$heights[1] <- unit(3, "cm")
  legend$grobs[[2]]$widths[1] <- unit(0.25, "cm")
  legend$grobs[[3]]$heights[1] <- unit(3, "cm")
  legend$grobs[[4]]$heights[1] <- unit(-3.348, "cm")
  legend$grobs[[4]]$widths[1] <- unit(2, "cm")
  
  
  p0_gtable <- ggplot_gtable(ggplot_build(p0))
  leg <- which(sapply(p0_gtable$grobs, function(x) x$name) == "guide-box")
  p0_gtable$grobs[[leg]] <- legend
  
  return(p0_gtable)
}

#generate figures#####
## show the 20 most significant GOBPs enriched in experimental group and control group.
pwnum <- 20
ggsave(filename = paste0("Figure 4 A",".png"),
       suppressWarnings(GO_point_plot("GO-ps",pwnum)),
       dpi = 300,
       height = 5,width = 8.5)
ggsave(filename = paste0("Figure S8 A",".png"),
       suppressWarnings(GO_point_plot("GO-fast",pwnum)),
       dpi = 300,
       height = 5,width = 8.5)
