#packages#####
suppressWarnings(suppressMessages(library(ggplot2)))
suppressWarnings(suppressMessages(library(tidyverse)))
suppressWarnings(suppressMessages(library(readxl)))
suppressWarnings(suppressMessages(library(ggnewscale)))
suppressWarnings(suppressMessages(library(grid)))
suppressWarnings(suppressMessages(library(ggrepel)))

#paths#####
ps_random <- read.csv("./PBMCSLEctrl-ps_cluster_top_gene100_KEGG_ctrl_summary[2000max].csv")
ps_exp <- read.csv("./PBMCSLEctrl-ps_cluster_top_gene100_KEGG_exper_summary[2000max].csv")
ps_exp_group <- read_excel("./pbmcctrl-ps-kegg-diseases-sle.xlsx",
                           sheet = "ps")%>%select("Description","Relation")
ps_random_group <- read_excel("./pbmcctrl-ps-kegg-diseases-sle.xlsx",
                             sheet = "random")%>%select("Description","Relation")
fast_random <- read.csv("./PBMCSLEctrl_cluster_top_gene100_KEGG_ctrl_summary.csv")
fast_exp <- read.csv("./PBMCSLEctrl_cluster_top_gene100_KEGG_exper_summary.csv")
fast_exp_group <- read_excel("./pbmcctrl-fast-kegg-diseases-sle.xlsx",
                           sheet = "fast")%>%select("Description","Relation")
fast_random_group <- read_excel("./pbmcctrl-fast-kegg-diseases-sle.xlsx",
                             sheet = "random")%>%select("Description","Relation")

#function####

#' Extracting the legend of a ggplot object.
#'
#' param a.gplot: a ggplot object.
#' return the legend of the ggplot object, a gtable object.
g_legend <- function(a.gplot){
   tmp <- ggplot_gtable(ggplot_build(a.gplot))
   leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
   legend <- tmp$grobs[[leg]]
   return(legend)
}

#' Performing KEGG pathway enrichment of top relevant genes clusters of PBMC-ctrl 
#' dataset generated by GeneClust-ps and GeneClust-fast.
#' 
#' param method: a character of the method to generate KEGG pathway enrichment.
#' param pwnum: the number of top significant KEGG pathways in experimental group
#'              and control group.
#' return gtable object.
KEGG_point_plot <- function(method,pwnum){
    ## choose data set
    if(method =="KEGG-ps"){
      random <- ps_random 
      exp <- ps_exp
      exp_group <- ps_exp_group 
      random_group <- ps_random_group
    }
    if(method =="KEGG-fast"){
      random <- fast_random 
      exp <- fast_exp
      exp_group <- fast_exp_group 
      random_group <- fast_random_group
    }
  
    ## extract needed rows and columns
    random <-random[1:pwnum,c("ID","Description","p.adjust","Count","auc")]
    exp <- exp[1:pwnum,c("ID","Description","p.adjust","Count","auc")]
    random[,'method'] <- "random"
    exp[,'method'] <- "gc"
    random <- left_join(as_tibble(random),random_group,by = "Description")
    exp <- left_join(as_tibble(exp),exp_group,by = "Description")
    
    random$count1 <- NA
    exp$count1 <- exp$Count
    random$count2 <- random$Count
    exp$count2 <- NA
    combine <- rbind(random,exp)
    
    ## change the color of text
    combine$IDcol <- "black"
    combine[combine$Description=="Systemic lupus erythematosus",'IDcol'] <- "red"
    combine[combine$Description=="Systemic lupus erythematosus",'ID'] <- 
    paste0(combine[combine$Description=="Systemic lupus erythematosus",'ID'],"(SLE)")
  
    combine[combine$Relation=="Marked",'Relation'] <- "Related"
    combine$recode <- ifelse(combine$Relation=="Related",49,99)
    
    ## generate plot
    pcc <- ggplot(combine,aes(x = -log10(p.adjust), y = auc))+
            geom_point(aes(size = count1),color = "transparent",shape = 19)+
            scale_size_continuous(limits = c(0,15),breaks = c(5,10,15),labels = c("","",""),
                                  range = c(-1.5,6),guide = guide_legend(order = 3,
                                                                         override.aes = list(color = "black"),
                                                                         title = "Count"))+
            new_scale("size")+
            geom_point(aes(size = count2),color = "transparent",shape = 17)+
            scale_size_continuous(limits = c(0,15),breaks = c(5,10,15),
                                  range = c(-1.5,6),guide = guide_legend(order = 4,
                                                                         override.aes = list(color = "black"),
                                                                         title = " "))+
            new_scale("size")+
            geom_point(aes(size = Count,color = recode,shape = method))+
            geom_text_repel(aes(label = ID),color = combine$IDcol,size = 2.5,max.overlaps = 30,
                            segment.size = 0.3,force = 5,segment.color = "grey40")+
            scale_size_continuous(limits = c(0,15),breaks = c(5,10,15),
                                  range = c(-1.5,6),guide = "none")+
            scale_shape_manual(values = c("gc"=19 ,"random"=17),
                               labels = c("Experiment","Control"))+
            labs(shape = "Method")+
            theme_classic()+ labs( x = "-log p.adjust", y = "AUC")+
            coord_cartesian(ylim = c(0,1),xlim = c(0.2,7),clip = "off")+
            scale_color_steps(breaks = c(50),limits = c(0,100),
                              labels = c(" "),high = "#ff7500" ,low = "#00e09e",
                              name = "",na.value = "transparent")+
            theme(axis.title = element_text(size = 12),
                  axis.text = element_text(size = 10,color = "black"),
                  legend.title = element_text(size = 12),
                  legend.background = element_rect(color= "transparent",fill = "transparent"),
                  legend.key= element_rect(color = "transparent", 
                                           fill = "transparent"),
                  legend.text = element_text(size = 10),
                  legend.position = "right",
                  plot.margin = unit(c(0.5,0.7,0.5,0.5),'cm'))+
            guides(shape = guide_legend(order = 1,override.aes = list(size = 2.5)),
                   color = guide_colorsteps(order = 2,reverse = T,barwidth = 1, barheight = 3),
                   fill = "none")
    pc <- pcc + annotate("text",label = "SLE-related",x = 8.5,y = 0.56)+
                annotate("text",label = "SLE-unrelated",x = 8.6,y = 0.487)


    ## legend adjustment
    legend <- g_legend(pc)
    legend$grobs[[1]]$heights[1] <- unit(3, "cm")
    legend$grobs[[2]]$heights[1] <- unit(3, "cm")
    legend$grobs[[2]]$widths[1] <- unit(0.25, "cm")
    legend$grobs[[3]]$heights[1] <- unit(3, "cm")
    legend$grobs[[4]]$heights[1] <- unit(-3.348, "cm")
    legend$grobs[[4]]$widths[1] <- unit(2, "cm")
    # grid.newpage()
    # grid.draw(legend)
    
    pc_gtable <- ggplot_gtable(ggplot_build(pc))
    leg <- which(sapply(pc_gtable$grobs, function(x) x$name) == "guide-box")
    pc_gtable$grobs[[leg]] <- legend
    
    return(pc_gtable)

}

#generate figures#####
## show The 20 most significant KEGG pathways in experimental group and control group
pwnum <- 20

ggsave(filename = paste0("Figure 5 A",".png"),
       suppressWarnings(KEGG_point_plot("KEGG-ps",pwnum)),
       dpi = 300,
       height = 5,width = 8.5)

ggsave(filename = paste0("Figure S9 A",".png"),
       suppressWarnings(KEGG_point_plot("KEGG-fast",pwnum)),
       dpi = 300,
       height = 5,width = 8.5)

